### ISSUE TITLE
Insert replaces line

### ISSUE THREAD

**Issue by chrismatheson** [jrowny/brackets-snippets#15]
i would like to be able to insert a snippit into current code without wipping out the line?

https://github.com/jrowny/brackets-snippets/blob/master/main.js#L89

there you start by deleting the whole line after the ctrl+v command is pressed. Could the extension start by matching first??

C

**Comment by jrowny** [comment]
That's a good idea but I'd like to preserve the inline-arguments functionality and I can't think of a reliable way to have both inline-arguments and the inline completion wizard without using an entire line. Otherwise I wouldn't know which parts of the line were arguments. I could make a setting to make them exclusive of each other... either you get inline arguments or inline snippets. Any Ideas?

**Comment by zaggino** [comment]
@chrismatheson @jrowny 
what about a separator sign before the trigger?
`f func` would behave like it behaves now
`$f func` would work inline

**Comment by jrowny** [comment]
Rather than a $ operator, could we make a setting in the snippet itself? Something as simple as <code>'inline':true</code>.

**Comment by zaggino** [comment]
Yes, but that would not allow parameters. On the other side, we will not probably have many parameters in one-liners. What about having both? Lets have `inline:true` in the settings and use `%f` (% instead of $ because $ is valid variable prefix in JS) if you want to use non-inline snippet in inline mode.

**Comment by jrowny** [comment]
sounds good to me.

**Comment by zaggino** [comment]
Implemented in #35

**Comment by jrowny** [comment]
closed with #35
