### ISSUE TITLE
Ctrl-Shift-S conflicts with 'Save As'

### ISSUE THREAD

**Issue by subhajitbn** [jrowny/brackets-snippets#19]
**Software:** Brackets Sprint 27
**OS:** Windows 8 Pro

**Problem:** `Ctrl-Shift-S` combination is mapped to `Save As` option and does not work for showing available snippets.

**Comment by lkcampbell** [comment]
@ajantrik,

Just an FYI, there is a new Brackets Key Remapper extension that just became available in the Extension Manager today which is a great workaround solution to this problem.  You can assign any shortcut key you want and avoid conflicts.

**Comment by clouddueling** [comment]
`Cannot assign Shift-Cmd-S to snippets.hideSnippets. It is already assigned to file.saveAs`
Brackets 33

**Comment by jrowny** [comment]
Looks like I need to change the default key, any suggestions?

**Comment by lkcampbell** [comment]
@jrowny, as you probably already know, any shortcut key is a potential future target for both the core team and other extension developers.  I toyed with the idea of using some really obscure key combination like CTRL-ALT-~ or CTRL-ALT-function key although I never tried them out since I ending up pulling my shortcut keys in the end, in hopes that the keyboard shortcut remapping functionality would be coming soon to the core product.

Maybe CTRL-SHIFT-4?  It would be equivalent to CTRL-$, which is _sort_ of like an S :).  $nippets!

Note, I haven't tested any of these weird ideas to make sure they are okay as keyboard shortcuts.

**Comment by clouddueling** [comment]
`Ctrl-Alt-V` conflicts with another extension and overrides this one.

I changed to this and it works but this is an extension vs. extension problem.
`Ctrl-Shift-V`

`Ctrl-Shift-A` appears to be available I just changed it in my own and it worked without conflicting with anything else that I currently have installed.

**Comment by RB-Lab** [comment]
I use `Ctrl-Alt-Space` to run snippet. It's like `Ctrl-Space` to show hints. I'm used to see snippets between hints as it made in Aptana. But anyway `Ctrl-Alt-Space` looks unoccupied and quite logical. And you cant press it with one hand. For 'show snippets' I use `Ctrl-Shift-4` as it suggested above. But I think that it is unnecessary at all. Because looking to snippets is not common task: if you use snippet often, you remember it's trigger; if you use snippet rarer - than you don't need that snippet.

**Comment by jrowny** [comment]
closed with #34
